version: "2.1"
services:
  frontend:
    build:
      context: ./frontendUpdated
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./demo
    ports:
      - "9192:9191"
    environment:
      MYSQL_HOST: mysqlservice
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: spedemo3
      MYSQL_USER: root
      MYSQL_PASSWORD: 0553
    depends_on:
      mysqlservice:
        condition: service_healthy
    networks:
      - app_network
    restart: always

  mysqlservice:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0553
      MYSQL_DATABASE: spedemo3
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
